version: '3.8'

services:
  api:
    container_name: mimou-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=2001
      - DB_NAME=mi
    